### ISSUE TITLE
[Python] Show API key regardless of whether or not model is trained

### ISSUE THREAD

**Issue by bendavis78** [IBM/taxinomitis#149]
There are some useful API functions (such as `/api/scratch/:scratchkey/train`) that can be used with a api key without needing a trained model. Right now you can't see the API key unless you train your model. So, if you were doing something like the Pacman activity, but in Python, you have no way to get the API key.

It would be good to show the API key at the top of the "Make" page so that it can be easily copied-and-pasted, regardless of whether or not a model is trained.

Students will eventually learn that is their "go-to" place whenever they need to find their API key. 

As a bonus, it would be great if it were in a text input similar to GitHub's repo URL box, where you can click the "copy to clipboard" button.

**Comment by dalelane** [comment]
That's a good point, thanks. I'll have a go at reworking the page.

**Comment by dalelane** [comment]
Closing as this is implemented now.
