### ISSUE TITLE
Create multiple student accounts at once

### ISSUE THREAD

**Issue by DGraveling** [IBM/taxinomitis#163]
Add the ability to create more than one student account at a time. And idea; the teacher could specify a generic ID e.g. the name of the school, and the number of accounts required. Then, automatically generate the users with username <ID><n>. For example, MySchool1, MySchool2, ..., MySchooln
Generating all the passwords may be tricky.

**Comment by dalelane** [comment]
@DGraveling Finally got time to work on this - sorry it took so long!
