### ISSUE TITLE
Can this be deployed to a shared host?

### ISSUE THREAD

**Issue by marklendl** [IBM/taxinomitis#174]
I'm a newbie to this and am trying to deploy to a domain on a shared hosting plan.

Is this possible? If so, are there any steps to guide me?

Thanks!

P.S. So, far I have copied the contents in the public folder to the website (cpanel) public_html folder.  But not sure what's the next step.

**Comment by ajdaniel** [comment]
I commend your effort to try and host this, but you will need to run this on a system like cloud foundry or kubernetes. It will need to be running on a NodeJS host.

However, you won't get very far without providing some client access tokens to gain access to some of the back-end services (like watson, or the database).

If you are really serious about hosting this yourself you will need to have a discussion with @dalelane around possibly gaining access to these restricted systems and databases. But I'm sure, for now, this codebase is not expected to be hosted anywhere other than `machinelearningforkids.com`

**Comment by dalelane** [comment]
@marklendl Unfortunately there is more to running the site then just hosting the source files. 

You'd need to build the site first, using the gulpfile or gruntfile in the root directory. That does a number of essential things, such as download the third-party dependencies that are also needed https://github.com/IBM/taxinomitis/blob/master/public/bower.json#L15-L33 

It also does some compiling and templating - some of the HTML and JS files in `public` include variables that are substituted in at build time, and the TypeScript source needs to be compiled into JavaScript.

When you build the site, the output will go into a `dist` folder, and that is the folder that needs to be hosted.

As Andrew says, there is also the back-end DB and REST API that needs to make up part of the site. That is a Node.js application so you need to run it in an environment that can run Node.js. When I'm running it on my laptop, I use `npm run local` to do this. https://github.com/IBM/taxinomitis/blob/master/package.json#L7 

You do need access to a MySQL database. If you want to host it yourself, the definition for the DB is at https://github.com/IBM/taxinomitis/blob/master/sql/tables.sql  - and again, when I'm working on the site on my laptop, I just run the database locally on my laptop, too.

There are a number of environment variables that are needed for the site to run. If you're running in a Cloud Foundry environment, you can see how to provide them at https://github.com/IBM/taxinomitis/blob/master/manifest-template.yml#L17-L43 
If you're running it any other Node.js environment, you can see the list of environment variables needed at https://github.com/IBM/taxinomitis/blob/master/src/lib/utils/env.ts#L29-L39  (This also divides them into essential and optional)

**Comment by marklendl** [comment]
Thanks guys. Based on what you said, this looks more complex than I initially thought  :-(  Anyways, I am particularly interested to replicate the website's functionality when it comes to creating projects, training (creating labels) as well as "learn and test".  Any suggestion on how this can be achieved in easier / simpler manner?  Thanks in advance.

**Comment by dalelane** [comment]
It's hard to know without knowing what you mean by "replicate the website's functionality". 

If you want to store/manage training data, you'll need somewhere to store it. If a database is too complex, do you have an alternative in mind?

**Comment by marklendl** [comment]
Hi Dale, thanks for responding.  I'm old school - so, database is fine - but the rest of what you said just seem a little alien to me right now.

**Comment by dalelane** [comment]
So you're unfamiliar with Node.js - is there a back-end language you prefer?

**Comment by marklendl** [comment]
If you are referring to server side language, i guess it would be PHP.

**Comment by dalelane** [comment]
You could re-implement the site in PHP - using PHP instead of Node.js to store and manage the training data. The ML models are created by submitting REST API calls to IBM Watson APIs, so those could stay largely as-is. 

That's not something I have time to help with, I'm afraid, so I'm going to close the issue. If you have any specific questions/issues driving the Watson APIs from PHP, please let me know - happy to help if I can.

**Comment by marklendl** [comment]
@kevinrobinson Thanks! Looks promising.  Will check it out.  Thanks again!
