### ISSUE TITLE
Worksheets page isn't fully translated

### ISSUE THREAD

**Issue by dalelane** [IBM/taxinomitis#176]
Tags, difficulty and project types aren't translated - so they are left as English text in an otherwise translated page. 

~And only English worksheets are linked to.~ _(This is fixed now)_

It'd be good to fix that.

**Comment by fbocquet** [comment]
let me know if you need french translation ;-)

**Comment by jptorino** [comment]
I may transalte to Spanish, in the comming months if it make sense.  For use we will be using them to Spanish speaker kids.  What would be the best way to do it?   Does it make sense or is it the intention to keep them in English?

**Comment by dalelane** [comment]
@jptorino Translations are always very welcome! If you're comfortable with editing JSON files, you can submit improvements directly to https://github.com/IBM/taxinomitis/blob/master/public/languages/es.json or if you prefer an editing interface you can use https://www.transifex.com/machine-learning-for-kids/machine-learning-for-kids/dashboard/ 

If there is something you'd find easier, please let me know though - I'm happy to try anything.
