### ISSUE TITLE
npm run test failed

### ISSUE THREAD

**Issue by AlexLiuXiaoting** [IBM/taxinomitis#188]
os: macOS 10.14.2 
node: v10.15.3
npm:  6.4.1
gulp:
CLI version: 2.2.0
Local version: 3.9.1
tsc v3.4.3

src/tests/notifications/emails.ts(76,24): error TS2345: Argument of type '(options: Options, defaults?: Options | undefined) => Mail' is not assignable to parameter of type '(transport: TransportOptions | Transport, defaults?: TransportOptions | undefined) => Mail'.
  Types of parameters 'options' and 'transport' are incompatible.
    Type 'TransportOptions | Transport' is not assignable to type 'Options'.
      Property 'pool' is missing in type 'TransportOptions' but required in type 'Options'.
src/tests/notifications/slack.ts(34,30): error TS2345: Argument of type 'undefined' is not assignable to parameter of type 'IncomingWebhookSendError'.
src/tests/notifications/slack.ts(43,42): error TS2345: Argument of type 'undefined' is not assignable to parameter of type 'IncomingWebhookResult'.
src/tests/restapi/scratch.ts(1120,83): error TS2345: Argument of type '(url: string, options?: CoreOptions | undefined) => RequestPromise' is not assignable to parameter of type '(options: (UriOptions & RequestPromiseOptions) | (UrlOptions & RequestPromiseOptions), callback?: RequestCallback | undefined) => RequestPromise'.
  Types of parameters 'url' and 'options' are incompatible.
    Type '(UriOptions & RequestPromiseOptions) | (UrlOptions & RequestPromiseOptions)' is not assignable to type 'string'.
      Type 'UriOptions & RequestPromiseOptions' is not assignable to type 'string'.
src/tests/restapi/scratch.ts(1191,83): error TS2345: Argument of type '(url: string, options?: CoreOptions | undefined) => RequestPromise' is not assignable to parameter of type '(options: (UriOptions & RequestPromiseOptions) | (UrlOptions & RequestPromiseOptions), callback?: RequestCallback | undefined) => RequestPromise'.
src/tests/restapi/scratch.ts(1279,83): error TS2345: Argument of type '(url: string, options?: CoreOptions | undefined) => RequestPromise' is not assignable to parameter of type '(options: (UriOptions & RequestPromiseOptions) | (UrlOptions & RequestPromiseOptions), callback?: RequestCallback | undefined) => RequestPromise'.
src/tests/restapi/scratch.ts(1336,83): error TS2345: Argument of type '(url: string, options?: CoreOptions | undefined) => RequestPromise' is not assignable to parameter of type '(options: (UriOptions & RequestPromiseOptions) | (UrlOptions & RequestPromiseOptions), callback?: RequestCallback | undefined) => RequestPromise'.
  Types of parameters 'url' and 'options' are incompatible.
    Type '(UriOptions & RequestPromiseOptions) | (UrlOptions & RequestPromiseOptions)' is not assignable to type 'string'.
      Type 'UriOptions & RequestPromiseOptions' is not assignable to type 'string'.
src/tests/training/conversation.ts(47,56): error TS2345: Argument of type '(url: string) => RequestPromise' is not assignable to parameter of type '(options: (UriOptions & RequestPromiseOptions) | (UrlOptions & RequestPromiseOptions), callback?: RequestCallback | undefined) => RequestPromise'.
  Types of parameters 'url' and 'options' are incompatible.
    Type '(UriOptions & RequestPromiseOptions) | (UrlOptions & RequestPromiseOptions)' is not assignable to type 'string'.
      Type 'UriOptions & RequestPromiseOptions' is not assignable to type 'string'.
src/tests/training/conversation.ts(48,9): error TS2322: Type 'SinonStub<[(UriOptions & RequestPromiseOptions) | (UrlOptions & RequestPromiseOptions), (RequestCallback | undefined)?], RequestPromise>' is not assignable to type 'SinonStub<[string, (RequestPromiseOptions | undefined)?, (RequestCallback | undefined)?], RequestPromise>'.
  Type '[(UriOptions & RequestPromiseOptions) | (UrlOptions & RequestPromiseOptions), (RequestCallback | undefined)?]' is not assignable to type '[string, (RequestPromiseOptions | undefined)?, (RequestCallback | undefined)?]'.
    Types of property '0' are incompatible.
      Type '(UriOptions & RequestPromiseOptions) | (UrlOptions & RequestPromiseOptions)' is not assignable to type 'string'.
        Type 'UriOptions & RequestPromiseOptions' is not assignable to type 'string'.
src/tests/training/conversation.ts(53,62): error TS2345: Argument of type '(url: string) => RequestPromise' is not assignable to parameter of type '(options: (UriOptions & RequestPromiseOptions) | (UrlOptions & RequestPromiseOptions), callback?: RequestCallback | undefined) => RequestPromise'.
  Types of parameters 'url' and 'options' are incompatible.
    Type '(UriOptions & RequestPromiseOptions) | (UrlOptions & RequestPromiseOptions)' is not assignable to type 'string'.
      Type 'UriOptions & RequestPromiseOptions' is not assignable to type 'string'.
src/tests/training/numbers.ts(31,62): error TS2345: Argument of type '(url: string, options?: CoreOptions | undefined) => RequestPromise' is not assignable to parameter of type '(options: (UriOptions & RequestPromiseOptions) | (UrlOptions & RequestPromiseOptions), callback?: RequestCallback | undefined) => RequestPromise'.
  Types of parameters 'url' and 'options' are incompatible.
    Type '(UriOptions & RequestPromiseOptions) | (UrlOptions & RequestPromiseOptions)' is not assignable to type 'string'.
      Type 'UriOptions & RequestPromiseOptions' is not assignable to type 'string'.
src/tests/training/visreccreds.ts(61,9): error TS2322: Type 'SinonStub<[(UriOptions & RequestPromiseOptions) | (UrlOptions & RequestPromiseOptions), (RequestCallback | undefined)?], RequestPromise>' is not assignable to type 'SinonStub<[string, (RequestPromiseOptions | undefined)?, (RequestCallback | undefined)?], RequestPromise>'.
src/tests/training/visreccreds.ts(63,9): error TS2322: Type 'SinonStub<[(UriOptions & RequestPromiseOptions) | (UrlOptions & RequestPromiseOptions), (RequestCallback | undefined)?], RequestPromise>' is not assignable to type 'SinonStub<[string, (RequestPromiseOptions | undefined)?, (RequestCallback | undefined)?], RequestPromise>'.
src/tests/training/visreccreds.ts(69,62): error TS2345: Argument of type '(url: string, opts?: CoreOptions | undefined) => RequestPromise' is not assignable to parameter of type '(options: (UriOptions & RequestPromiseOptions) | (UrlOptions & RequestPromiseOptions), callback?: RequestCallback | undefined) => RequestPromise'.
  Types of parameters 'url' and 'options' are incompatible.
    Type '(UriOptions & RequestPromiseOptions) | (UrlOptions & RequestPromiseOptions)' is not assignable to type 'string'.
      Type 'UriOptions & RequestPromiseOptions' is not assignable to type 'string'.
src/tests/training/visualrecognition.ts(58,9): error TS2322: Type 'SinonStub<[(UriOptions & RequestPromiseOptions) | (UrlOptions & RequestPromiseOptions), (RequestCallback | undefined)?], RequestPromise>' is not assignable to type 'SinonStub<[string, (RequestPromiseOptions | undefined)?, (RequestCallback | undefined)?], RequestPromise>'.
src/tests/training/visualrecognition.ts(63,9): error TS2322: Type 'SinonStub<[(UriOptions & RequestPromiseOptions) | (UrlOptions & RequestPromiseOptions), (RequestCallback | undefined)?], RequestPromise>' is not assignable to type 'SinonStub<[string, (RequestPromiseOptions | undefined)?, (RequestCallback | undefined)?], RequestPromise>'.
src/tests/training/visualrecognition.ts(68,62): error TS2345: Argument of type '(url: string) => RequestPromise' is not assignable to parameter of type '(options: (UriOptions & RequestPromiseOptions) | (UrlOptions & RequestPromiseOptions), callback?: RequestCallback | undefined) => RequestPromise'.
  Types of parameters 'url' and 'options' are incompatible.
    Type '(UriOptions & RequestPromiseOptions) | (UrlOptions & RequestPromiseOptions)' is not assignable to type 'string'.
      Type 'UriOptions & RequestPromiseOptions' is not assignable to type 'string'.
TypeScript: 17 semantic errors
TypeScript: emit succeeded (with errors)
[00:45:14] Finished 'images' after 14 s
[00:45:14] Starting 'web'...
[00:45:14] Finished 'web' after 56 μs
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ml-for-kids@0.0.1 test: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ml-for-kids@0.0.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by dalelane** [comment]
Thanks for letting me know. I believe this should be resolved now by the changes in https://github.com/IBM/taxinomitis/commit/75bf190e96b64f2b11f6cc57eac10d3ae3e83719
