### ISSUE TITLE
can not find scratch3 project

### ISSUE THREAD

**Issue by AlexLiuXiaoting** [IBM/taxinomitis#193]
I got confused that I can not find the Scratch3 project, Could you help me? Many thanks!

gulp.task('scratch3install', ['crossdomain'], function() {
return gulp.src([
'public/scratch3/**',
'public/components/help/help-scratch3*',
'public/components/help/help-scratch.css'
]).pipe(gulp.dest('web/scratch3'));
});

I cant not find any public/scratch3/ file from git repository.

**Comment by dalelane** [comment]
Scratch 3 lives at https://github.com/LLK
