### ISSUE TITLE
taxinomitis-numbers source code

### ISSUE THREAD

**Issue by bigmikesmile** [IBM/taxinomitis#199]
Hi it is amazing project ,  I got stuck when deployed taxinotitis-numbers instance, could you share taxinomitis source code?

**Comment by kursattuncel** [comment]
I just saw that, my issue was actually related with this issue.  Can you share the details of the numbers service (not just describe-model)?

**Comment by hidaris** [comment]
@dalelane ping

**Comment by garrapato** [comment]
Any news regard this question? I'm trying to deploy  the site but I'm stucked also with this issue

Thanks in advance for your help

**Comment by dalelane** [comment]
Sorry, all - combination of both work and personal commitments means I've been too busy to work on ML for Kids issues recently.
