### ISSUE TITLE
Error: not implemented 

### ISSUE THREAD

**Issue by mahmoudtarek1871997** [IBM/taxinomitis#202]
sound recognition.. when I press "start listening" it gives me that error

**Comment by dalelane** [comment]
Hello. Please can you give me a few details? 

What type of web browser are you using?
What type of computer are you using?
What web page were you on?

**Comment by dalelane** [comment]
@mahmoudtarek1871997 If you can get some more details on this, I'd be happy to have a look - please re-open it if you do come back to it.
