### ISSUE TITLE
Design for larger class sizes

### ISSUE THREAD

**Issue by dalelane** [IBM/taxinomitis#203]
My original design assumed a teacher who leads a class. So the UI is based on an assumption that there will be at most 30 students in the class list. 

It does work with larger groups.... sort of. (There is a hard limit of 254 students in a class because of the data type used to store the limit).

Increasingly I'm getting requests for schools that ask for a class of 100 students or 200 students. While this is do-able, I'm not sure it's a great experience. It'd be worth looking into what could be done to make this better.

**Comment by MrMazzone** [comment]
After speaking with many teachers, they definitely want to be able to manage more students.  I believe these educators do not have class sizes over 30 students. In reality, they would like to support multiple classes and need to be able to manage more than 30 students. For example, two classes of 25.  How I managed this in the classroom was each of my 20 computers stations essentially had an account that students shared between classes. This however can get tricky when you have students work on many ML for Kids projects. 

My suggestion is a feature where teacher accounts can create multiple classes. Under student management you would first create a class/course/group and name it, then you can add"new student" or "multiple students" to that selected group.

Then you can define the max number of students per class and the max number of classes a teacher account can have. I am not sure what those limits need to be.

**Comment by dalelane** [comment]
<img width="1410" alt="Screenshot 2020-11-06 at 11 02 43" src="https://user-images.githubusercontent.com/1444788/98359139-a3da4d80-201f-11eb-8ffc-e62a8b79e466.png">

![image](https://user-images.githubusercontent.com/1444788/98359176-afc60f80-201f-11eb-8a11-b0be13ba6e7f.png)

![image](https://user-images.githubusercontent.com/1444788/98359235-c8cec080-201f-11eb-9968-05b1a96b503d.png)

<img width="1410" alt="Screenshot 2020-11-06 at 11 04 56" src="https://user-images.githubusercontent.com/1444788/98359312-eef46080-201f-11eb-82d5-931cd56e177c.png">

**Comment by rhelmstedter** [comment]
I teach middle school in the United States. I have 6 classes in total, two of which are computer Science. One of those has 31 students, the other has 37. I would definitely appreciate the option for more students.

**Comment by dalelane** [comment]
@rhelmstedter This isn't so much about an option for more students - which is already possible (please email me your class details and I can update your class) - but about improving the usability for managing larger classes.
