### ISSUE TITLE
Feature Request: External Scratch Extension

### ISSUE THREAD

**Issue by MrMazzone** [IBM/taxinomitis#209]
Many Scratch teachers were requesting a Scratch extension that could be used on https://scratch.mit.edu/ and maybe published here http://scratchx.org/#home

The reason for this request was that the educators (and they predict their students) would like to be able to keep the Scratch project on their account and then would be able to share with the community.  Also, if students had an exisiting project that they would like to improve with ML, this could be useful.  The teachers understood that implementing/using this external extension may create a hassle of copy and pasting a project key into some kind of initialization block at the start of the program. They seemed comfortable with this and mentioned that the extension would be for specialized situations and more advanced students.

Not sure how easy it would be to take your existing Scratch extension and publish it to be used on the general Scratch 3 site.  Also, not sure if you would be able to generate the extension with the project key in a similar way you do with the App Inventor extension, so users do not have to copy and paste the project key.

Implementation suggestion:
Additional project "Make" category with an option for "External Scratch 3 Project - Use an Extension to connect your machine learning model to an existing Scratch project".

**Comment by dalelane** [comment]
re: Scratch 3 - They haven't released support for external extensions yet, so there's nothing I can do until then. When they do announce formal extension support, this will definitely be worth revisiting though!

**Comment by dalelane** [comment]
re: ScratchX - Unfortunately, Scratch will only allow extensions from github.io and coding.me 

https://github.com/LLK/scratch-flash/blob/2e4a402ceb205a042887f54b26eebe1c2e6da6c0/src/extensions/ExtensionManager.as#L57-L62

If MIT could be persuaded to add `machinelearningforkids.co.uk` to that list, then it could work. I don't think ScratchX is under active development any more, so getting any change accepted (let alone this) could be a challenge? Not sure.

**Comment by MrMazzone** [comment]
@ewpatton can you direct us to someone on the Scratch team that can help us out?

**Comment by garrapato** [comment]
Hi @MrMazzone, we are currently developing extensions for our version of ScrtachX (GARRAX), which includes extensions to various IBM Watson services (Assistant, Translator, Tone Analyzer, Visual Recognition), and an extension to control the IBM TJBot via Bluetooth, and that allows you to use the dynamically generated extensions by Machine Learnig to Kids, if you are interested visit our site (Beta) at: https://Garragames.com/es/garrax

**Comment by MrMazzone** [comment]
Hi @garrapato, thank you for reaching out.  Looks like you have done some great work!

**Comment by dalelane** [comment]
@garrapato Thanks for the links - that looks really good. Did you have any ideas about what integration with Machine Learning for Kids might look like?

**Comment by dalelane** [comment]
Closing as I don't think this is something that the Scratch Team will want to support
