### ISSUE TITLE
ERROR 1071 (42000) at line 68: Specified key was too long; max key length is 3072 bytes

### ISSUE THREAD

**Issue by nijisakai** [IBM/taxinomitis#225]
**macOS 10.14**
**mysql version==5.7**
**using brew install mysql@5.7**

$  `~/taxinomitis(master*) » mysql -u root --password=password < sql/tables.sql`

**got error:** ERROR 1071 (42000) at line 68: Specified key was too long; max key length is 3072 bytes

**Comment by dalelane** [comment]
@nijisakai Do you know what the full MySQL version is, please? 
I'd assume that pulling 5.7 got you 5.7.27 - is that right?

**Comment by dalelane** [comment]
The reason I ask is because I haven't been able to recreate the problem.

I pulled the public Docker image for MySQL 5.7
`docker pull mysql/mysql-server:5.7` 

Ran a new clean container using the image
`docker run --name=mysql01 -p 127.0.0.1:8888:3306 -e MYSQL_ROOT_PASSWORD=password -e MYSQL_ROOT_HOST=%  -d mysql/mysql-server:5.7`

And then ran a MySQL client pointing to `mysql://root:password@localhost:8888`

And it was able to run the `tables.sql` statements without any errors.

So my assumption is that you're using some sub-version of 5.7 that is different to the 5.7.27 that I got.

**Comment by nijisakai** [comment]
**Thank you @dalelane !**

this is the info:

```
~/taxinomitis(master*) » mysql -u root -p                                                                                                                          niji@localhost
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 104
Server version: 5.7.27 Homebrew

Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
```

Somehow after i changed the **imageurl** from 1024 to 768, it seemed work.

```
CREATE TABLE imagetraining (
    id CHAR(36) NOT NULL PRIMARY KEY,
    projectid CHAR(36) NOT NULL,
    imageurl VARCHAR(768) NOT NULL,
    label VARCHAR(100),
    isstored BOOLEAN DEFAULT false
);
```

**Comment by dalelane** [comment]
A related symptom from the same user was this unit test failure:


```
1) DB store
       storeProject
         should recognise SQL errors about unsupported characters:

      AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
+ expected - actual

- 'Should not have stored a project with this name'
+ 'Sorry, some of those letters can\'t be used in project names'
      + expected - actual
```

**Comment by dalelane** [comment]
Changes to the column size in the table definition would need a corresponding change to https://github.com/IBM/taxinomitis/blob/master/src/lib/db/objects.ts#L255 otherwise the mismatch will cause errors

**Comment by dalelane** [comment]
@nijisakai I think I know what caused the problem. Please could you pull the latest version of the code and try again?

**Comment by nijisakai** [comment]
**Thank you @dalelane ! It worked.**


mysql: v5.7.27 (dmg file from official website)
nodejs: v10.16.3 (dmg file from official website)
os: macOS 10.13.6
