### ISSUE TITLE
Problems with ML Scratch blocks in Edge

### ISSUE THREAD

**Issue by dalelane** [IBM/taxinomitis#244]
No details yet - don't know if this is ScratchX or Scratch 3, which project types, etc. 

But it sounds like there is a problem somewhere with MS Edge.

**Comment by Portabella** [comment]
We had a workshop with eight laptops at the same time. Two laptops worked with the MS Edge browser. For them the ML4Kids Scratch 3.0 version worked as long as there was no ML model connected / part of the code. 

We used Text recognition. 

As soon as we used ML4kids blocks, the program got stuck and would not continue. 

We only had this problem with the Edge browser. 
![broken version (with ML blocks)](https://user-images.githubusercontent.com/2048569/63757558-93c2cc00-c8ba-11e9-8b94-b346cb48b767.png)
![working version (no ML blocks)](https://user-images.githubusercontent.com/2048569/63757560-945b6280-c8ba-11e9-880f-74c18ad50ce7.png)

**Comment by dalelane** [comment]
@Portabella Thanks for the update - I think part of the problem might be a problem with the Scratch script/code.

Looking at the screenshot, it's using the blocks that return the machine learning model's confidence (rather than the label). 

So the equals checks are doing a comparison of the percentage confidence score in classifying the answer text (e.g. `85`)  with the word `nett` or `gemain`. 

Both of those if checks can never pass, so the result would be that the script would appear to do nothing. 

If you replace the `recognize text ... (confidence)` blocks with `recognize text ... (label)` blocks, does that work?

**Comment by Portabella** [comment]
Sorry for the confusion - this are just quick sceenshots I made this morning in order to show the problem. The original code in the Edge browser was correct and didn't "compile". 

It worked for all other browsers. 

For now we will just tell workshop participants to not use Edge browser.

**Comment by dalelane** [comment]
I haven't been able to reproduce the problem - would you be able to send me a copy of an sb3 Scratch project file that demonstrates the issue, please?

**Comment by Portabella** [comment]
I don’t have the original files anymore - it was on the participants computers. I only have versions that are working. If it happens again I will try to do send it to you and/or send you a short demo of the problem. 

Thanks for your help!

**Comment by dalelane** [comment]
Did some more testing and still couldn't find any problems - I'll close the issue for now and will re-open if I get an example to investigate.
