### ISSUE TITLE
Error: Not implemented

### ISSUE THREAD

**Issue by basab11** [IBM/taxinomitis#262]
Project Name: Alien     While training/ recognizing sounds (using Firefox browser on Ubuntu Mate) I am repeatedly getting the message Error: Not Implemented.

As a result, the accuracy of the training model is compromised. Have tried different sound variation with larger data set but same the error keeps coming each time the "Learn & Test" option is executed.

Looking forward to your kind help and support to resolve the issue.

**Comment by dalelane** [comment]
> While training/ recognizing sounds (using Firefox browser on Ubuntu Mate) 

Do you mean you only see the error on Firefox on Ubuntu? Does using a different web browser show the same problems?

> I am repeatedly getting the message Error: Not Implemented.

Do you mean you're getting that error from this page?

![image](https://user-images.githubusercontent.com/1444788/65353613-7ba64a00-dbe5-11e9-9735-fe4c3e0c3ae7.png)

When do you get that error? (Can you describe the exact steps that recreate the problem, please?)

By "repeatedly" do you mean that it happens every time? Or only some times?

> As a result, the accuracy of the training model is compromised. 

I'm not quite sure what you mean by that. 

> Have tried different sound variation with larger data set but same the error 
> keeps coming each time the "Learn & Test" option is executed.

Do you mean you're seeing errors on this page? 

![image](https://user-images.githubusercontent.com/1444788/65353749-cd4ed480-dbe5-11e9-85c7-6d894f49db63.png)

What error do you get? When do you get that error? (Can you describe the exact steps that recreate the problem, please? Is it when you click on Train? Or Start Listening?)

**Comment by dalelane** [comment]
Closing as it's not possible to investigate this without details.
