### ISSUE TITLE
Right-to-left language support

### ISSUE THREAD

**Issue by mapmeld** [IBM/taxinomitis#267]
Hi - if a translator comes forward for Arabic, Hebrew, Persian, Urdu, or another right-to-left language, I'm open to setting up the appropriate layout / stylesheet for it

Currently the mysql2 issue is keeping me from popping up my own local instance, but I would work through or around it if there is a specific translation goal

**Comment by dalelane** [comment]
Thanks for the offer!

I'll try and get the [MySQL update](https://github.com/IBM/taxinomitis/issues/82#issuecomment-546695990) tested soon to unblock you at least

**Comment by dalelane** [comment]
Closing this as I still haven't had any translations that would allow this to be progressed
