### ISSUE TITLE
NUMBERS_SERVICE, NUMBERS_SERVICE_USER, NUMBERS_SERVICE_PASS

### ISSUE THREAD

**Issue by kursattuncel** [IBM/taxinomitis#276]

**Comment by kursattuncel** [comment]
Hi,

I think there is problem with numbers service.

Under serverless-functions/mltraining-numbers, 

# mltraining-numbers
- DescribeModel
    - Input:
        - Training data for numbers ML project
    - Output:
        - JSON object containing representations of the decision tree classifier (png, dot, svg)

DescribeModel is provided by this function.

However, there is nothing in the code that, numbers training is using this model.
All I see is the referecense to 
NUMBERS_SERVICE, NUMBERS_SERVICE_USER, NUMBERS_SERVICE_PASS 
which are completely unknown.

what are the correct parameters to deploy numbers service?

**Comment by kursattuncel** [comment]
Duplicate of #199

**Comment by summerscar** [comment]
I have the same problem
