### ISSUE TITLE
ML for kids API Keys for visual recognition error 

### ISSUE THREAD

**Issue by ravichas** [IBM/taxinomitis#291]
Hello,

I've sucessfully registered the "**Watson Assistant**" API Key however when tried to add the "Visual Recognition" API  Key I got the following error: "**_Error: Watson credentials could not be verified_**".  I followed the instructions from the manual, machinelearningforkids-apikeys.pdf. 
Any help would be greatly appreciated.

Thanks,
Ravi

**Comment by dalelane** [comment]
closing as I'll [answer it in Google Groups instead](https://groups.google.com/forum/#!topic/mlforkids/HzxFMQeQD3U)
