### ISSUE TITLE
Replace moment.js with something smaller

### ISSUE THREAD

**Issue by dalelane** [IBM/taxinomitis#371]
Moment.js is loaded in the UI but only used in one place (to display how long ago a model status was checked). It's a very large dependency for every page considering that only a tiny bit of it is used in only one place.

I'd like to remove it and replace it with something smaller like https://github.com/iamkun/dayjs

The dependency is defined here:
https://github.com/IBM/taxinomitis/blob/533994cb17fd71f306c382f5a2b2de7129b9584d/public/bower.json#L21

It's added to the UI page here:
https://github.com/IBM/taxinomitis/blob/533994cb17fd71f306c382f5a2b2de7129b9584d/public/index.html#L119
https://github.com/IBM/taxinomitis/blob/533994cb17fd71f306c382f5a2b2de7129b9584d/public/index.html#L131

It's only used here:
https://github.com/IBM/taxinomitis/blob/533994cb17fd71f306c382f5a2b2de7129b9584d/public/components/models/models.html#L443

**Comment by gabrielcbe** [comment]
I don't know if this would help in when using these bower components, but when using regular es6 imports in npm, you could use something like https://www.npmjs.com/package/babel-plugin-transform-imports in babel (probably during gulp) to import only the functions of the library you're using.
