### ISSUE TITLE
how to get the API KEY ( error : API key isn't a machine learning for kids key )

### ISSUE THREAD

**Issue by karlTH** [IBM/taxinomitis#403]
Hello, i've try many things but i don't arrive to have an apikey who work.

Wheni'm going on : [https://machinelearningforkids.co.uk/#!/teacher/apikeys](https://machinelearningforkids.co.uk/#!/teacher/apikeys)
They say : no apiket need for images cmlassification
I've been on : [https://cloud.ibm.com/](https://cloud.ibm.com/)
I've create an account and get an apikey like it's say here  :  
[https://raw.githubusercontent.com/IBM/taxinomitis-docs/master/docs/pdf/machinelearningforkids-apikeys.pdf](https://raw.githubusercontent.com/IBM/taxinomitis-docs/master/docs/pdf/machinelearningforkids-apikeys.pdf)
With this apikey in app inventor : 
the block error return the error : API key isn't a machine learning for kids key

What should i do ? and how
Thanks a lot

**Comment by dalelane** [comment]
Please just ask the question in one place - this is the third time I've seen this question this evening

**Comment by dalelane** [comment]
As you were told in one of the other threads where you asked, the App Inventor extension does not use IBM Cloud API keys. That's what "isn't a Machine Learning for Kids key" is referring to. It will only work with API keys from the Machine Learning for Kids website. It will not work with API keys from the IBM Cloud website.
