### ISSUE TITLE
Add an icon to the language selector button

### ISSUE THREAD

**Issue by EvanSmith93** [IBM/taxinomitis#412]
The button for letting the end user select their language simply says "Language" (In English). Would it be appreciated if I added an icon next to the word "Language" to make it easier for those who don't speak the language to find it? One option is the icon from languageicon.org, but there are plenty others.

**Comment by dalelane** [comment]
That's a nice idea, thanks - I hadn't heard of that languageicon.org before.

If it helps, the language menu source is here: https://github.com/IBM/taxinomitis/blob/f2a3204847d8f49172d28b9bd77e74acaea3f76e/public/index.html#L72-L98
