### ISSUE TITLE
the project is doesn't work

### ISSUE THREAD

**Issue by Machine03** [IBM/taxinomitis#423]
according to The first step to last step finish , but run the npm start command, the err like this images
running the command:
![1626763816633](https://user-images.githubusercontent.com/15908331/126275068-ed4d4ff7-7e14-42ba-a475-625150467fb2.jpg)
web message:
![1626763874660](https://user-images.githubusercontent.com/15908331/126275093-0f42574a-f979-48e4-8988-c9677febeba6.jpg)
docker log:
![1626763803190](https://user-images.githubusercontent.com/15908331/126275102-031c5370-4f32-4b40-b580-429de39377bf.jpg)

please help ~. thankful bro

**Comment by dalelane** [comment]
Did you follow the instructions in https://github.com/IBM/taxinomitis/blob/master/DEVELOPMENT.md ?

**Comment by Machine03** [comment]
yes am sure am follow the&nbsp;DEVELOPMENT.md&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dale ***@***.***&gt;; 
发送时间: 2021年7月20日(星期二) 下午4:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [IBM/taxinomitis] the project is doesn&#39;t work (#423)





 
Did you follow the instructions in https://github.com/IBM/taxinomitis/blob/master/DEVELOPMENT.md ?
 
&mdash;

**Comment by Machine03** [comment]
and this video&nbsp;https://www.youtube.com/watch?v=Ss3e6yCWOhU




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dale ***@***.***&gt;; 
发送时间: 2021年7月20日(星期二) 下午4:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [IBM/taxinomitis] the project is doesn&#39;t work (#423)





 
Did you follow the instructions in https://github.com/IBM/taxinomitis/blob/master/DEVELOPMENT.md ?
 
&mdash;

**Comment by dalelane** [comment]
The reason I asked was that your screenshot seems to show you're using Node.js v12, and the first step in DEVELOPMENT.md is to use Node.js v14

I'm not sure what the docker.log refers to, but if you have a log from your server (in the logs folder) I'd be happy to take a look

**Comment by Machine03** [comment]
this is my log .....&nbsp; &nbsp;the msg:404
{"name":"ml-for-kids","hostname":"af23b0628a60","pid":5632,"level":30,"req":{"method":"GET","url":"/","headers":{"host":"localhost:3000","connection":"keep-alive","cache-control":"max-age=0","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","sec-fetch-site":"none","sec-fetch-mode":"navigate","sec-fetch-user":"?1","sec-fetch-dest":"document","sec-ch-ua":"\" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"91\", \"Chromium\";v=\"91\"","sec-ch-ua-mobile":"?0","accept-encoding":"gzip, deflate, br","accept-language":"zh-CN,zh;q=0.9"},"remoteAddress":"172.17.0.1","remotePort":61712},"res":{"statusCode":200,"header":null},"msg":"404","time":"2021-07-21T01:06:16.062Z","src":{"file":"/tmp/taxinomitis/dist/lib/restapi/errors.js","line":83},"v":0}
{"name":"ml-for-kids","hostname":"af23b0628a60","pid":5632,"level":30,"req":{"method":"GET","url":"/","headers":{"host":"localhost:3000","connection":"keep-alive","cache-control":"max-age=0","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","sec-fetch-site":"none","sec-fetch-mode":"navigate","sec-fetch-user":"?1","sec-fetch-dest":"document","sec-ch-ua":"\" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"91\", \"Chromium\";v=\"91\"","sec-ch-ua-mobile":"?0","accept-encoding":"gzip, deflate, br","accept-language":"zh-CN,zh;q=0.9"},"remoteAddress":"172.17.0.1","remotePort":61712},"res":{"statusCode":200,"header":null},"msg":"404","time":"2021-07-21T01:06:16.073Z","src":{"file":"/tmp/taxinomitis/dist/lib/restapi/errors.js","line":83},"v":0}
{"name":"ml-for-kids","hostname":"af23b0628a60","pid":5632,"level":30,"req":{"method":"GET","url":"/","headers":{"host":"localhost:3000","connection":"keep-alive","cache-control":"max-age=0","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","sec-fetch-site":"none","sec-fetch-mode":"navigate","sec-fetch-user":"?1","sec-fetch-dest":"document","sec-ch-ua":"\" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"91\", \"Chromium\";v=\"91\"","sec-ch-ua-mobile":"?0","accept-encoding":"gzip, deflate, br","accept-language":"zh-CN,zh;q=0.9"},"remoteAddress":"172.17.0.1","remotePort":61712},"res":{"statusCode":200,"header":null},"msg":"404","time":"2021-07-21T01:06:16.088Z","src":{"file":"/tmp/taxinomitis/dist/lib/restapi/errors.js","line":83},"v":0}





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dale ***@***.***&gt;; 
发送时间: 2021年7月21日(星期三) 凌晨0:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [IBM/taxinomitis] the project is doesn&#39;t work (#423)





 
The reason I asked was that your screenshot seems to show you're using Node.js v12, and the first step in DEVELOPMENT.md is to use Node.js v14
 
I'm not sure what the docker.log refers to, but if you have a log from your server (in the logs folder) I'd be happy to take a look
 
&mdash;

**Comment by dalelane** [comment]
Could I have the whole log, uploaded as a file, rather than a copy/pasted snippet please?

**Comment by Machine03** [comment]
ok am upload the file already.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dale ***@***.***&gt;; 
发送时间: 2021年7月21日(星期三) 下午4:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [IBM/taxinomitis] the project is doesn&#39;t work (#423)





 
Could I have the whole log, uploaded as a file, rather than a copy/pasted snippet please?

**Comment by dalelane** [comment]
Can you check the contents of your web folder please?

```sh
ls web/static/*
```

**Comment by Machine03** [comment]
i don't understand what you mine, chenk my web folder?  I installed it according to the installation instructions and the docker images and the version , i check the project is didn't have file of the web/static 😿

**Comment by dalelane** [comment]
step 5 in https://github.com/IBM/taxinomitis/blob/master/DEVELOPMENT.md is to run the build which generates the web folder

If you don't have a web folder, it means you either forgot to do this step or this step failed and you didn't notice the errors. 

Please can you try that step again, and if you see errors, could you share them?

**Comment by Machine03** [comment]
OK i re execute the setp 5 for now , The error message is:


bower webcam#3.2.1&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;download https://github.com/jonashartmann/webcam-directive/archive/3.2.1.tar.gz
bower angular-timeago#0.4.6&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;error ETIMEDOUT
bower angular-timeago#0.4.6&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;retry Download of https://github.com/yaru22/angular-timeago/archive/0.4.6.tar.gz failed with ETIMEDOUT, retrying in 1.4s
bower webcam#3.2.1&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; error ETIMEDOUT
bower webcam#3.2.1&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; retry Download of https://github.com/jonashartmann/webcam-directive/archive/3.2.1.tar.gz failed with ETIMEDOUT, retrying in 1.2s





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dale ***@***.***&gt;; 
发送时间: 2021年7月22日(星期四) 下午4:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [IBM/taxinomitis] the project is doesn&#39;t work (#423)





 
step 5 in https://github.com/IBM/taxinomitis/blob/master/DEVELOPMENT.md is to run the build which generates the web folder
 
If you don't have a web folder, it means you either forgot to do this step or this step failed and you didn't notice the errors.
 
Please can you try that step again, and if you see errors, could you share them?
 
&mdash;

**Comment by dalelane** [comment]
Thanks for sharing the resolution. 

To summarise, you haven't built the web site because you have connection problems accessing github.com
If you can correct the networking issues on your system, and re-run the build, then you should have a working site.
