### ISSUE TITLE
[Bug] Facial Detection detects objects in scene

### ISSUE THREAD

**Issue by JohnsonMyton** [IBM/taxinomitis#444]
Hello,
I've been using MachineLearningForKids for our Year 9 students.
When testing the Emoji Mask worksheet and the facial detection extension, I found that the emoji mask would never stay on a face, it would always end up drifting. When it drifts off the face, it then "resets" back onto the face again. I think that the facial detection extension is also picking up the emoji as a face, and so the emoji is positioning itself onto where it thinks it's emoji is.

I've used the Scratch Labs version of the lesson for now, but I'd love to use this version so students can train and add a "Facial Expression" model to have the emoji change depending on how the person looks.

**Comment by JohnsonMyton** [comment]
Hello, 
I've been using MachineLearningForKids for our Year 9 students. 
When testing the Emoji Mask worksheet and the facial detection extension, I found that the emoji mask would never stay on a face, it would always end up drifting. When it drifts off the face, it then "resets" back onto the face again. I think that the facial detection extension is also picking up the emoji as a face, and so the emoji is positioning itself onto where it thinks it's emoji is. 

I've used the Scratch Labs version of the lesson for now, but I'd love to use this version so students can train and add a "Facial Expression" model to have the emoji change depending on how the person looks.

**Comment by dalelane** [comment]
Thanks for the heads-up - I think you're right. It's using the combined image of everything on the Stage, including all sprites that are on top of the backdrop.

I'm fairly sure there are some projects that have taken advantage of this behaviour, so I'm reluctant to break them by changing it. 

Instead, I've added a new option for when using the webcam, that will ignore any sprites on top of the webcam or backdrop, and should fix the problem you describe.

<img width="398" alt="image" src="https://user-images.githubusercontent.com/1444788/160212192-073075fe-600d-4d5b-a583-b2962a97f5c2.png">

I'll need to update the worksheets to tell people to use this new option too.

Thanks again for letting me know!
