### ISSUE TITLE
AppInventor support

### ISSUE THREAD

**Issue by dalelane** [IBM/taxinomitis#46]
https://twitter.com/Math_CS_Teach/status/1016001945641811970

<img width="606" alt="image" src="https://user-images.githubusercontent.com/1444788/42422538-12f76ac0-82e0-11e8-9b1f-64cbbec9ea54.png">

[MIT AppInventor](https://github.com/IBM/taxinomitis/issues/11) is a bit Scratch-like but lets you build apps that can be deployed to Android devices. And according to this, soon to iOS devices, too.

In the same way that it was easy to [add Python support](https://github.com/IBM/taxinomitis/issues/11) by re-purposing the existing APIs for the Scratch extension, it might be worth looking into how AppInventor could drive the same API. 

If it's not too complicated, it could be very nice to allow students to write machine-learning-powered apps that they can run on a mobile phone.

**Comment by dalelane** [comment]
looks like it supports extensions
http://ai2.appinventor.mit.edu/reference/other/extensions.html

**Comment by dalelane** [comment]
Not sure if this is a good idea or not. 

It's a bit cliched to start uncontrollably adding features to software that's been around for a while. I'm concerned about over-complicating things. 

I'm already not loving the shove-the-Python-button-in approach...

<img width="1680" alt="screen shot 2018-07-09 at 19 46 08" src="https://user-images.githubusercontent.com/1444788/42469986-17ce5906-83b1-11e8-9476-a0dcb80fe129.png">

*If* I do this, it needs to be in a way that doesn't clutter up the current core workflow

**Comment by ajdaniel** [comment]
I like this idea. I don’t think it will clutter up the application. That page though, might get busy. I think the core items: train, learn & test, and scratch should remain, but python and additional “clients” can live behind an “advanced” button, or something like that. 

Appinventor sounds great as a client extension for ML4K, do you know how much usage it has worldwide and Uk?

**Comment by dalelane** [comment]
a comment here: https://twitter.com/adamcohenrose/status/1017745254022250499 

Got me looking at alternatives... it seems that there are a number of forks and distributions of AppInventor around : https://groups.google.com/forum/#!topic/ai4a/ajG4Q6UrRR8 

My gut says that building on the base open-source AppInventor project would be the best approach, rather than picking a distribution. But I know nothing about the differences between them yet.

**Comment by dalelane** [comment]
@ewpatton Thanks for getting in touch!

I'd forgotten to update this issue, but since this thread started someone has started work on AppInventor support. It's being developed separately over at https://github.com/kylecorry31/ML4K-AI-Extension but I'd like to get this added into the Machine Learning for Kids UI this week. 

I'd be interested to see what else people have done with AppInventor and Watson though - I couldn't find anything when I searched.

**Comment by MrMazzone** [comment]
@dalelane I am the Master Trainer @ewpatton is referring to! 

Evan, keep an eye out for when Dale adds App Inventor support to the ML for Kids UI. Feel free to check out the extension's repo and give it a try before that if you like.

**Comment by dalelane** [comment]
<img width="700" alt="screen shot 2018-08-16 at 00 56 32" src="https://user-images.githubusercontent.com/1444788/44179564-5d6f4000-a0ef-11e8-97bc-119cb92782c1.png">
