### ISSUE TITLE
Error: The credentials for the machine learning server used by your class were rejected

### ISSUE THREAD

**Issue by rocketbhoom** [IBM/taxinomitis#47]
Uhhhhhhh.......

What do I do here?

Thanks

**Comment by dalelane** [comment]
@rocketbhoom The API key that you provided for the Watson Visual Recognition service isn't valid. (You can verify this by trying it at https://watson-visual-recognition.ng.bluemix.net/ ) 

If you can go back to the API keys page in the Teacher tab (https://machinelearningforkids.co.uk/#!/teacher/apikeys ) then you delete that API key and replace it with a working one.

**Comment by rocketbhoom** [comment]
Thanks!
