### ISSUE TITLE
Bug: MQTT block can't load saved project

### ISSUE THREAD

**Issue by Lewiscowles1986** [IBM/taxinomitis#480]
Please find attached two saved scratch workspaces using the music and MQTT snippets

[Archive 2.zip](https://github.com/IBM/taxinomitis/files/12287259/Archive.2.zip)

This is really cool. I Just think maybe the kids will want to be able to save and load the projects as well.

![image](https://github.com/IBM/taxinomitis/assets/2605791/4ad13580-07f9-41f8-b62c-b62b86a353eb)

**Comment by dalelane** [comment]
Sorry about this

I can see that the zip contains two Scratch files - both with the MQTT blocks, and one of them loads fine and the other doesn't. 

Can you give me any clues about what differs between the two Scratch projects? Did you create them differently? Can you think of anything that you did differently between them that might explain why one loads and the other doesn't?

**Comment by Lewiscowles1986** [comment]
Does one of them load for you? Neither load for me. I had just created the second as a test.

**Comment by dalelane** [comment]
https://github.com/IBM/taxinomitis/assets/1444788/6cde70d7-0bb7-4810-9fb9-a02c9501fe50

**Comment by Lewiscowles1986** [comment]
Oh, how weird, it did load the second time. I might have to break out a debugger on this. Maybe an exception escapes and can tell me what is wrong. Thanks, and sorry for using your time to show me that. I was unaware one loaded. It didn't this AM, but then maybe I loaded the wrong file...

**Comment by Lewiscowles1986** [comment]
<details>
<summary>Traceback</summary>

```
gui {"validationError":"Could not parse as a valid SB2 or SB3 project.","sb2Errors":[{"keyword":"required","dataPath":"","schemaPath":"#/required","params":{"missingProperty":"objName"},"message":"should have required property 'objName'"}],"sb3Errors":[{"keyword":"type","dataPath":".targets[0].variables['`jEk@4|i[#Fk?(8x)AV.-my variable'][1]","schemaPath":"#/definitions/stringOrNumber/oneOf/0/type","params":{"type":"string"},"message":"should be string"},{"keyword":"type","dataPath":".targets[0].variables['`jEk@4|i[#Fk?(8x)AV.-my variable'][1]","schemaPath":"#/definitions/stringOrNumber/oneOf/1/type","params":{"type":"number"},"message":"should be number"},{"keyword":"oneOf","dataPath":".targets[0].variables['`jEk@4|i[#Fk?(8x)AV.-my variable'][1]","schemaPath":"#/definitions/stringOrNumber/oneOf","params":{"passingSchemas":null},"message":"should match exactly one schema in oneOf"},{"keyword":"type","dataPath":".targets[0].variables['`jEk@4|i[#Fk?(8x)AV.-my variable'][1]","schemaPath":"#/oneOf/1/type","params":{"type":"boolean"},"message":"should be boolean"},{"keyword":"oneOf","dataPath":".targets[0].variables['`jEk@4|i[#Fk?(8x)AV.-my variable'][1]","schemaPath":"#/oneOf","params":{"passingSchemas":null},"message":"should match exactly one schema in oneOf"}]}
```

</details>

So it is a schema validation error. Hmm.

**Comment by dalelane** [comment]
I can't recreate this and am fairly sure that load/save is working correctly so I'm closing this
