### ISSUE TITLE
mlforkids-api: Changes on Angular Component & Lang Translation not Reflected on The Browser

### ISSUE THREAD

**Issue by aamuzakii** [IBM/taxinomitis#488]
Hello, I'm relatively new to Angular and Gulp, transitioning from the React and Next.js environment.

I've encountered an issue while customizing some components and language translations. I made modifications in the public/components and public/languages folders. Afterward, I ran `npx gulp web`, `npm run build`, `npm run build_notest`, `npm run buildprod` to ensure everything was bundled correctly.

I can observe the changes in the `web/static/components` directory. However, when I run `npm run start` & navigate to browser localhost:3000, the UI doesn't reflect the modifications and there isn't any error messages. I've attempted to resolve the issue by running `npm cache clean`, but the problem persists.

It's worth noting that changes in the backend (src/lib) work as expected.

Any guidance on resolving this issue would be greatly appreciated. Thank you, and may luck be with you!

Additional info:
1. node version: v20.11.0
2. npm version: 10.2.4
3. I've read the DEVELOPMENT.md & watch the youtube developer guide

**Comment by dalelane** [comment]
Did you try clearing your browser cache?

**Comment by aamuzakii** [comment]
works like magic 😂
thanks for covering my silly blind spot 🙏🙏
