### ISSUE TITLE
A small opinion

### ISSUE THREAD

**Issue by GaleaWong** [IBM/taxinomitis#63]
Hello, when you are training, the title of the small topic will not be changed, only the option will be changed. This is very bad.

**Comment by dalelane** [comment]
Could you explain what you mean by "small topic" please? What option is changed?

**Comment by dalelane** [comment]
@GaleaWong Sorry - I don't understand the issue here. Could you explain it a little more, or perhaps add a screenshot or example, please?

**Comment by GaleaWong** [comment]
Sorry, it may be my network problem. No problem. I disturb you.

**Comment by GaleaWong** [comment]
Thank you
