### ISSUE TITLE
Watson API Keys Non-Hidden Password

### ISSUE THREAD

**Issue by scottcurtis2605** [IBM/taxinomitis#74]
When entering the Watson API keys for Watson Assistant, when entering username/password credentials, the password field is not hidden. I have provided a picture below to demonstrate this.

<img width="622" alt="screen shot 2018-08-22 at 15 07 22" src="https://user-images.githubusercontent.com/41568419/44468651-9c385500-a61d-11e8-9d89-b0953f5a5e93.png">

In addition, when adding an API key for the Watson Visual Recognition, you are not given the choice to log in with username/password credentials - only an API key. Not sure if this is intentional, or an issue.

<img width="587" alt="screen shot 2018-08-22 at 15 07 39" src="https://user-images.githubusercontent.com/41568419/44468668-a5292680-a61d-11e8-91db-915b57960384.png">

**Comment by dalelane** [comment]
Closing as I'd prefer to leave the current behaviour.
