### ISSUE TITLE
NLS for the models page

### ISSUE THREAD

**Issue by dalelane** [IBM/taxinomitis#90]
The biggest chunk of text that still needs moving across to the NLS files is here:
https://github.com/IBM/taxinomitis/blob/master/public/components/models/models.html#L47-L324 

I've been putting it off because it's poorly structured for NLS purposes, as it's got embedded text everywhere. But I really need to just get it done, as it's notable by it's absence when viewing the site in non-English mode.

**Comment by gabrielcbe** [comment]
Is it possible to use a translation engine for the areas that are currently not present in the NLS files? (as long as it's not too much work to implement)
Not the optimum solution but it would be a work-around whilst people haven't finished the translation for the whole file (or are still hard-coded).

**Comment by dalelane** [comment]
Interesting idea.... something like [this](https://github.com/tewen/gtd-scripts/blob/master/translate-json) might be a way to do it.
